### PR TITLE
fix image local loading issue and add new line for headers

### PR DESCRIPTION
**Pull request by agate**
Hi @Avik-Jain ,

Thanks for the great ML learning course! I noticed that Github is not allowing user to use blob url for rendering the image `https://github.com/Avik-Jain/100-Days-Of-ML-Code/blob/master/Other%20Docs/data.PNG` (unless you are rendering it from github website). I cloned your repo to local and open it via my markdown editor and I found the editor was not able to correctly render the images. And it turns out that you have to use `raw` instead of `blob` for fixing this problem. So I made this PR.

BRs,
Hao.

### CODE REVIEW

**Comment by MirroZhou** [comment]
谢谢~已收到！

**Comment by Cherrie52** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，您的邮件我已经收到，我将尽快跟您回复！！

**Comment by wengJJ** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by dqhf** [comment]
你的来信已收到，谢谢！

**Comment by bghfcd19900** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
